language: php

php:
  - 7.0
  - hhvm

before_install:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist && make sniff

after_script:
  - php vendor/bin/coveralls -v
